yml client web

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -36,7 +36,7 @@ jobs:
         working-directory: web
 
       - name: Start Web Client
-        run: npm start
+        run: npm start &
         working-directory: web
 
   test-server:
@@ -46,6 +46,16 @@ jobs:
       - name: Check if Server is Running
         run: |
           response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
+          if [ "$response" == "200" ]; then
+            echo "Server is running successfully."
+          else
+            echo "Server is not running or responding with an error."
+            exit 1
+          fi
+      
+      - name: Check if Web Client is Running
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
           if [ "$response" == "200" ]; then
             echo "Server is running successfully."
           else
