escuta servidor

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -6,25 +6,63 @@ on:
       - actions
 
 jobs:
-  cypress-run:
+  start-server:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Install Dependencies - Server
+        run: npm install
+        working-directory: server
+
+      - name: Show DB_ENV
+        run: |
+          echo "DB_ENV=${{ secrets.DB_ENV }}" > server/.env
+          
+      - name: Start Server
+        run: npm start &
+        working-directory: server
+
+  start-web-client:
+    needs: start-server
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        
+      - name: Install Dependencies - Web
+        run: npm install
+        working-directory: web
+
+      - name: Start Web Client
+        run: npm start
+        working-directory: web
+
+  test-server:
+    needs: start-server
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if Server is Running
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
+          if [ "$response" == "200" ]; then
+            echo "Server is running successfully."
+          else
+            echo "Server is not running or responding with an error."
+            exit 1
+          fi
+
+  run-tests:
+    needs: [start-server, start-web-client, test-server]
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Install Dependencies
-        run: npm install
+
       - name: Run Cypress Tests
         uses: cypress-io/github-action@v6
         with:
-          build: npm run build
-          start: npm run start
           install: true
-          working-directory: web
-          runTests: false
-      - name: Run Cypress Tests
-        uses: cypress-io/github-action@v6
-        with:
-          install: false
-          working-directory: .
