script checar servidor

diff --git a/.github/workflows/start-worflow.yml b/.github/workflows/start-worflow.yml
--- a/.github/workflows/start-worflow.yml
+++ b/.github/workflows/start-worflow.yml
@@ -24,32 +24,21 @@ jobs:
         run: npm start &
         working-directory: server
 
-      - name: Wait for Server to Start
-        run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
-          if [ "$response" == "200" ]; then
-            echo "Server is running successfully."
-          else
-            echo "Server is not running or responding with an error."
-            exit 1
-          fi
-
-
   start-web-client:
     needs: start-server
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-        
+            
       - name: Install Dependencies - Web
         run: npm install
         working-directory: web
-
+            
       - name: Start Web Client
         run: npm start &
         working-directory: web
-      
+            
       - name: Check if Web Client is Running
         run: |
           response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
@@ -57,5 +46,15 @@ jobs:
             echo "Web Client is running successfully."
           else
             echo "Web Client is not running or responding with an error."
+            exit 1
+          fi
+      
+      - name: Wait for Server to Start
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
+          if [ "$response" == "200" ]; then
+            echo "Server is running successfully."
+          else
+            echo "Server is not running or responding with an error."
             exit 1
           fi
