wait for server

diff --git a/.github/workflows/start-worflow.yml b/.github/workflows/start-worflow.yml
--- a/.github/workflows/start-worflow.yml
+++ b/.github/workflows/start-worflow.yml
@@ -24,16 +24,23 @@ jobs:
         run: npm start &
         working-directory: server
 
-      - name: Check if Server is Running
+      - name: Wait for Server to Start
         run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
-          if [ "$response" == "200" ]; then
-            echo "Server is running successfully."
-          else
-            echo "Server is not running or responding with an error."
-            exit 1
-          fi
-      
+          max_attempts=30
+          attempt=0
+          while [ $attempt -lt $max_attempts ]; do
+            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
+            if [ "$response" == "200" ]; then
+              echo "Server is running successfully."
+              exit 0
+            else
+              echo "Server is not running yet. Waiting..."
+              sleep 5
+              ((attempt++))
+            fi
+          done
+          echo "Server did not start within the timeout period."
+          exit 1
 
   start-web-client:
     needs: start-server
@@ -54,8 +61,8 @@ jobs:
         run: |
           response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
           if [ "$response" == "200" ]; then
-            echo "Server is running successfully."
+            echo "Web Client is running successfully."
           else
-            echo "Server is not running or responding with an error."
+            echo "Web Client is not running or responding with an error."
             exit 1
-            fi
+          fi
